CREATE TEMPORARY TABLE DIVI_STAGING
/* CREATE TABLE DIVI_STAGING */
(
	bene_source_id int,
	bene_classe varchar(200),
	bene_tipo varchar(200), 
	bene_denominazione varchar(255),
	bene_data_utimo_aggiornamento datetime(3),
	bene_hash varchar(64),
	dc_tipo_catasto varchar(1),
	dc_codice_catastale varchar(4),
	dc_sezione_censuaria varchar(3),
	dc_sezione_urbana varchar(3),
	dc_foglio varchar(5),
	dc_particella varchar(10),
	dc_subalterno varchar(6),
	dc_tipo_immobile varchar(50),
	dc_hash varchar(64),
	ente_denominazione varchar(255),
	ente_sigla varchar(30),
	ente_cf varchar(16),
	ente_pi varchar(11),
	ente_hash varchar(64),
	loc_regione varchar(50),
	loc_provincia varchar(50),
	loc_comune varchar(50),
	loc_indirizzo varchar(120),
	loc_civico varchar(20),
	loc_lat decimal(10,7),
	loc_lon decimal(10,7),
	loc_hash varchar(64),
	prov_id_atto varchar(60),
	prov_tipo varchar(60),
	prov_data date,
	prov_hash varchar(64),
	batch_id bigint
);